# Generated by Django 4.2.3 on 2023-07-25 17:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_alter_order_order_date'),
    ]

    operations = [
        migrations.RenameField(
            model_name='orderprod',
            old_name='order_id',
            new_name='order',
        ),
        migrations.RenameField(
            model_name='orderprod',
            old_name='product_id',
            new_name='product',
        ),
    ]
