# Generated by Django 4.2.3 on 2023-07-21 21:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='photos',
        ),
    ]
