# Generated by Django 4.2.3 on 2023-07-21 21:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_alter_category_options_alter_product_categores_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='categores',
            field=models.ManyToManyField(blank=True, related_name='prodcuts', to='products.category'),
        ),
    ]
