# Generated by Django 4.2.3 on 2023-07-24 13:31

from django.db import migrations, models
import django.db.models.deletion
import products.models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_product_stock_quantity'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='photo',
            name='product_id',
        ),
        migrations.AddField(
            model_name='photo',
            name='product',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='poduct_p', to='products.product'),
        ),
        migrations.AlterField(
            model_name='photo',
            name='photo',
            field=models.ImageField(default='', upload_to=products.models.get_photo_upload_path),
        ),
        migrations.AlterField(
            model_name='product',
            name='name',
            field=models.CharField(blank=True, default='', max_length=100, null=True),
        ),
    ]
