# Generated by Django 4.2.3 on 2023-07-24 13:37

from django.db import migrations, models
import products.models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0007_alter_photo_product_alter_product_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='photo',
            name='photo',
            field=models.ImageField(upload_to=products.models.get_photo_upload_path),
        ),
    ]
